# Generated by Django 4.2.5 on 2023-09-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_img_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='img',
            new_name='Img',
        ),
    ]
